# Generated by Django 3.1.7 on 2021-03-02 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(blank=True, max_length=128, null=True)),
                ('company', models.CharField(blank=True, max_length=128, null=True)),
                ('street_english', models.CharField(blank=True, max_length=128, null=True)),
                ('street_chinese', models.CharField(blank=True, max_length=128, null=True)),
                ('country', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=128, null=True)),
                ('state', models.CharField(blank=True, max_length=128, null=True)),
                ('accounting_attention_person', models.CharField(blank=True, max_length=128, null=True)),
                ('account_email', models.EmailField(blank=True, max_length=64, null=True)),
                ('purchase_attention_person', models.CharField(blank=True, max_length=128, null=True)),
                ('purchase_email', models.EmailField(blank=True, max_length=64, null=True)),
                ('phone', models.EmailField(blank=True, max_length=64, null=True)),
                ('vat', models.EmailField(blank=True, max_length=64, null=True)),
                ('is_agent', models.BooleanField(blank=True, null=True)),
                ('brands', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.mainbuyer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=128, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=128, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=64, null=True)),
                ('order_number', models.CharField(blank=True, max_length=64, null=True)),
                ('supplier_code', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Localbuyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('company_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.companyinfo')),
                ('customer_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.customerdetail')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
