# Generated by Django 3.1.7 on 2021-03-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_companyinfo_customerdetail_localbuyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='fax',
            field=models.EmailField(blank=True, max_length=64, null=True),
        ),
    ]
