# Generated by Django 3.1.7 on 2021-03-21 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_shippingaddress_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='PiList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(blank=True, max_length=32, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pi_user', to='ecommerce.localbuyer')),
            ],
        ),
        migrations.CreateModel(
            name='PiOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.order')),
                ('pi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.pilist')),
            ],
        ),
    ]
