# Generated by Django 3.1.7 on 2021-03-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_pilist_piorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pistatus',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
